version: '3.1'

services:

  test:
    environment:
      - DOCKER_ENV=1
    build: .
    image: python:3.9.7
    volumes:
      - .:/app
    command: make test
    links:
      - "postgres:postgres_host"

  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: zenaida_db_user
      POSTGRES_PASSWORD: zenaida_db_user
      POSTGRES_DB: zenaida_db_01
