version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202101-01
    steps:
      - checkout
      - run:
          name: "Use Python v3.8.7"
          command: |
            pyenv versions
            pyenv global 3.8.7
      - run:
          name: "Build"
          command: |
            make docker/test
