version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: "Use Docker Compose"
          command: |
            docker-compose -v
      - run:
          name: "Build"
          command: |
            make docker/test
